remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Birds Birds Birds Competition
description: A Kaggle Image Classification Competition as CSE 455 Final
